name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install dependencies
        run: ./gradlew dependencies
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: TestApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk

